### ISSUE TITLE
compress two time matrices using hdf5 standard compression

### ISSUE THREAD

**Issue by sureshnaps** [AdvancedPhotonSource/xpcs-eigen#5]
Implement compression while saving two time datasets - minor but
saves 2x space for files on the disk that run into 10-20 GB level. Standard hdf5 built in compression is good.

**Comment by iamfaisalkhan** [comment]
We now have a compression for two-time result matrices. Added a compression flag to functions within h5result for optionally enabling compression for any output dataset.
