### ISSUE TITLE
Setting up CI

### ISSUE THREAD

**Issue by danielballan** [AdvancedPhotonSource/xpcs-eigen#8]
We discussed on a phone call today setting up CI for this project so that we can verify that future changes do not break existing use cases.

Speaking for myself, I'd be happy with any of the popular CI services, but we at NSLS-II have the most experience debugging Travis-CI.

If an owner of this repository can activate Travis, we can iterate from there, contributing tests and other useful checks via pull request. This documentation, although addressed to Python users, may be a useful starting point: https://nsls-ii.github.io/scientific-python-cookiecutter/ci.html

**Comment by danielballan** [comment]
Bump. Can someone click this button? https://travis-ci.org/AdvancedPhotonSource/xpcs-eigen/

**Comment by sureshnaps** [comment]
Says it is not an active repository

**Comment by iamfaisalkhan** [comment]
@danielballan I just clicked the link. I will also add you as to this repo.

**Comment by danielballan** [comment]
Closed by #14
